version: "3"
services:
  pg_master_1:
     build: ./master
     ports:
         - "5401:5432"
     volumes:
         - ./mdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
         - PG_REP_USER=replica
         - PG_REP_PASSWORD=rep^Cca@123
     networks:
           - bridge-docker
     restart: always
  pg_slave_1:
     build: ./slave
     ports:
         - "5402:5432"
     volumes:
         - ./sdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
         - PG_REP_USER=replica
         - PG_REP_PASSWORD=rep^Cca@123
     networks:
           - bridge-docker
     restart: always
volumes:
  mdata:
  sdata:
networks:
  bridge-docker:
    external:
      name: bridge-docker
